# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllStarsV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging’

  # Pods for AllStarsV2

end
